// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0c3ryatVN-r7kIsTmYZPBlgHj5E4x-E',
    appId: '1:547378520398:web:28b064f66c4350ec4e7e1f',
    messagingSenderId: '547378520398',
    projectId: 'quizlet-clone-8c1fe',
    authDomain: 'quizlet-clone-8c1fe.firebaseapp.com',
    storageBucket: 'quizlet-clone-8c1fe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwr9sxKLJr83ieKq8Z1RVUfulfNGCmILU',
    appId: '1:547378520398:android:bbf789716e21d7a74e7e1f',
    messagingSenderId: '547378520398',
    projectId: 'quizlet-clone-8c1fe',
    storageBucket: 'quizlet-clone-8c1fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01mzZqe5VRd7I97YyRSUD4g5vlnsUrHI',
    appId: '1:547378520398:ios:b92a8e57bf606d504e7e1f',
    messagingSenderId: '547378520398',
    projectId: 'quizlet-clone-8c1fe',
    storageBucket: 'quizlet-clone-8c1fe.appspot.com',
    iosBundleId: 'com.example.quizletFlashcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01mzZqe5VRd7I97YyRSUD4g5vlnsUrHI',
    appId: '1:547378520398:ios:b92a8e57bf606d504e7e1f',
    messagingSenderId: '547378520398',
    projectId: 'quizlet-clone-8c1fe',
    storageBucket: 'quizlet-clone-8c1fe.appspot.com',
    iosBundleId: 'com.example.quizletFlashcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj0c3ryatVN-r7kIsTmYZPBlgHj5E4x-E',
    appId: '1:547378520398:web:09de388f9ef53e614e7e1f',
    messagingSenderId: '547378520398',
    projectId: 'quizlet-clone-8c1fe',
    authDomain: 'quizlet-clone-8c1fe.firebaseapp.com',
    storageBucket: 'quizlet-clone-8c1fe.appspot.com',
  );
}
